# Generated by Django 5.2.6 on 2025-11-17 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_parkinglot_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingApprovalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='parking_approval_images/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_solicitud', to='parking.parkingapprovalrequest')),
            ],
        ),
    ]
