# Generated by Django 5.2.7 on 2025-11-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parkingimage_es_principal_parkingimage_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='plazas_disponibles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='tarifa_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='total_plazas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
