# Generated by Django 5.2.6 on 2025-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parkingapprovalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal del estacionamiento', null=True, upload_to='parking_main_images/'),
        ),
    ]
