# Generated by Django 5.2.7 on 2025-11-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_parkingapprovalrequest_plazas_disponibles_and_more'),
        ('parking', '0011_parkinglot_imagen_principal'),
    ]

    operations = [
    ]
