# Generated by Django 5.2.7 on 2025-11-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_merge_20251119_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingimage',
            name='es_principal',
        ),
        migrations.RemoveField(
            model_name='parkingimage',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='plazas_disponibles',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingapprovalrequest',
            name='total_plazas',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
