# Generated by Django 5.2.7 on 2025-11-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_remove_parkingimage_es_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='precio_dia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por día completo (24 horas)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='precio_mes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por mes completo (30 días)', max_digits=8, null=True),
        ),
    ]
