# Generated by Django 5.2.7 on 2025-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_parkinglot_precio_dia_parkinglot_precio_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreview',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingreview',
            name='motivo_reporte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingreview',
            name='reportado',
            field=models.BooleanField(default=False),
        ),
    ]
