# Generated by Django 5.2.6 on 2025-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_car_options_alter_user_options_alter_user_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, default='Perú', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('carnet_extranjeria', 'Carnet de Extranjería')], max_length=20, null=True),
        ),
    ]
