# Generated by Django 5.2.7 on 2025-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_codigo_postal_user_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
